---

variables:
    NODE_VERSION: 16
    DOCKER_YAMLLINT_VERSION: 2.0.0

include:
-   project: f4/gitlab-ci-tools
    ref: master
    file: /templates/node-js.yml

test:
    script:
    - npm run test
